---
info:
  description: Spring Cloud Config Repo
  url: https://github.com/spring-cloud-samples
endpoints:
   health:
     sensitive: false
---
spring:
  profiles: cloud
eureka:
  instance:
     nonSecurePort: 80

---
spring:
  profiles: local
eureka:
  instance:
    nonSecurePort: ${server.port}
